name: gitaction-codedeploy-cicd-project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.5.1

      
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash
      
      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

